fix lints and remove stupid files

diff --git a/.github/workflows/automated-checks.yml b/.github/workflows/automated-checks.yml
--- a/.github/workflows/automated-checks.yml
+++ b/.github/workflows/automated-checks.yml
@@ -3,17 +3,17 @@ name: Tests
 on:
   push:
     branches:
-      - '**'
+      - "**"
 
     tags-ignore:
-      - '**'
+      - "**"
 
   pull_request:
     branches:
-      - '**'
+      - "**"
 
     tags-ignore:
-      - '**'
+      - "**"
 
 jobs:
   # pre-commit Checks
@@ -32,10 +32,10 @@ jobs:
         run: nix profile install nixpkgs#devenv
       - name: Build the devenv shell and run any git hooks
         run: devenv test
-  
+
   # Run Test Coverage
   test-coverage:
-    needs: [ pre-commit ]
+    needs: [pre-commit]
     name: Test Coverage (Python ${{ matrix.python-version }})
     runs-on: ubuntu-latest
 
@@ -43,11 +43,11 @@ jobs:
       # Set Python and Django version to test for the stable release of AllianceAuth
       matrix:
         python-version:
-          - '3.8'
-          - '3.9'
-          - '3.10'
-          - '3.11'
-          - '3.12'
+          - "3.8"
+          - "3.9"
+          - "3.10"
+          - "3.11"
+          - "3.12"
 
     steps:
       - name: Checkout
@@ -73,32 +73,32 @@ jobs:
         # Run tox using the version of Python in `PATH`
         run: tox -v
 
-#      - name: Upload Coverage
-#        if: ${{
-#              (
-#                github.event_name == 'pull_request'
-#                || (
-#                  github.event_name == 'push'
-#                  && github.ref == 'refs/heads/master'
-#                )
-#              )
-#              && (
-#                matrix.python-version == '3.10'
-#                && matrix.database == 'mariadb:10.11'
-#              )
-#            }}
-#        uses: codecov/codecov-action@v3
-#        with:
-#          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
-#          files: coverage.xml # optional
-##          flags: unittests # optional
-##          name: codecov-umbrella # optional
-##          fail_ci_if_error: true # optional (default = false)
-#          verbose: true # optional (default = false)
+  #      - name: Upload Coverage
+  #        if: ${{
+  #              (
+  #                github.event_name == 'pull_request'
+  #                || (
+  #                  github.event_name == 'push'
+  #                  && github.ref == 'refs/heads/master'
+  #                )
+  #              )
+  #              && (
+  #                matrix.python-version == '3.10'
+  #                && matrix.database == 'mariadb:10.11'
+  #              )
+  #            }}
+  #        uses: codecov/codecov-action@v3
+  #        with:
+  #          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
+  #          files: coverage.xml # optional
+  ##          flags: unittests # optional
+  ##          name: codecov-umbrella # optional
+  ##          fail_ci_if_error: true # optional (default = false)
+  #          verbose: true # optional (default = false)
 
   # Pypi Build Test
   pypi-build-test:
-    needs: [ test-coverage ]
+    needs: [test-coverage]
     name: PyPi Build Test
     runs-on: ubuntu-latest
 
@@ -109,7 +109,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version-file: 'pyproject.toml' # Read the Python version from the pyproject.toml file
+          python-version-file: "pyproject.toml" # Read the Python version from the pyproject.toml file
 
       - name: Install Tools
         run: |
